<?php

use App\Menu;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class SeedMenuTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('menus', function (Blueprint $table) {
            \Illuminate\Support\Facades\DB::table('menus')->truncate();
            $data = [
                [
                    'menu_id' => null,
                    'name' => 'Institute',
                    'uri' => '/',
                    'type' => 1,
                    'order' => 2,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 2,
                    'name' => 'About Institute',
                    'uri' => '/',
                    'type' => 1,
                    'order' => 1,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 3,
                    'name' => 'Introduction',
                    'uri' => '/introduction',
                    'type' => 1,
                    'order' => 1,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 3,
                    'name' => 'Governing Body',
                    'uri' => '/governing-body',
                    'type' => 1,
                    'order' => 2,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 3,
                    'name' => 'Founder & Donor',
                    'uri' => '/founder-n-donor',
                    'type' => 1,
                    'order' => 3,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 2,
                    'name' => 'Administrative Message',
                    'uri' => '/',
                    'type' => 1,
                    'order' => 2,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 7,
                    'name' => 'President Message',
                    'uri' => '/president',
                    'type' => 1,
                    'order' => 1,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 7,
                    'name' => 'Principal Message',
                    'uri' => '/principal',
                    'type' => 1,
                    'order' => 2,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 2,
                    'name' => 'Infrastructure',
                    'uri' => '/',
                    'type' => 1,
                    'order' => 3,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 10,
                    'name' => 'Building & Rooms',
                    'uri' => '/building-room',
                    'type' => 1,
                    'order' => 4,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 10,
                    'name' => 'Library',
                    'uri' => '/library',
                    'type' => 1,
                    'order' => 5,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 10,
                    'name' => 'Transport',
                    'uri' => '/transport',
                    'type' => 1,
                    'order' => 6,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 10,
                    'name' => 'Hostel',
                    'uri' => '/hostel',
                    'type' => 1,
                    'order' => 7,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 10,
                    'name' => 'Land Information',
                    'uri' => '/land-information',
                    'type' => 1,
                    'order' => 7,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 2,
                    'name' => 'Academics',
                    'uri' => '/',
                    'type' => 4,
                    'order' => 4,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 16,
                    'name' => 'Class Routine',
                    'uri' => '/class-routine',
                    'type' => 1,
                    'order' => 1,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 16,
                    'name' => 'Academic Calendar',
                    'uri' => '/calendar',
                    'type' => 1,
                    'order' => 2,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 16,
                    'name' => 'Syllabus',
                    'uri' => '/syllabus',
                    'type' => 1,
                    'order' => 3,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 16,
                    'name' => 'Dairy',
                    'uri' => '/dairy',
                    'type' => 1,
                    'order' => 4,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 16,
                    'name' => 'Performance',
                    'uri' => '/performance',
                    'type' => 1,
                    'order' => 5,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 16,
                    'name' => 'Annual Holiday List',
                    'uri' => '/holiday',
                    'type' => 1,
                    'order' => 5,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 2,
                    'name' => 'Digital Campus',
                    'uri' => '/',
                    'type' => 4,
                    'order' => 5,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 23,
                    'name' => 'Multimedia Class Room',
                    'uri' => 'multimedia-classroom',
                    'type' => 1,
                    'order' => 1,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 23,
                    'name' => 'Computer Lab',
                    'uri' => 'computer-lab',
                    'type' => 1,
                    'order' => 2,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 23,
                    'name' => 'Science Lab',
                    'uri' => 'science-lab',
                    'type' => 1,
                    'order' => 3,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => null,
                    'name' => 'Team',
                    'uri' => '/',
                    'type' => 4,
                    'order' => 3,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 27,
                    'name' => 'Managing Committee',
                    'uri' => '/managing-committee',
                    'type' => 1,
                    'order' => 1,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 27,
                    'name' => 'Teachers',
                    'uri' => '/teacher',
                    'type' => 1,
                    'order' => 2,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 27,
                    'name' => 'Staff',
                    'uri' => '/staff',
                    'type' => 1,
                    'order' => 3,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 27,
                    'name' => 'Women Abuse Prevention Committee',
                    'uri' => '/wapc',
                    'type' => 1,
                    'order' => 4,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 27,
                    'name' => 'Teacher & Staff Welfare Trust',
                    'uri' => '/tswt',
                    'type' => 1,
                    'order' => 5,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 27,
                    'name' => 'Teachers Council Information',
                    'uri' => '/tci',
                    'type' => 1,
                    'order' => 6,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => null,
                    'name' => 'Result',
                    'uri' => '/',
                    'type' => 4,
                    'order' => 4,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 34,
                    'name' => 'Internal Result',
                    'uri' => 'internal-exam',
                    'type' => 1,
                    'order' => 1,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 34,
                    'name' => 'Public Examination',
                    'uri' => 'public-exam',
                    'type' => 1,
                    'order' => 2,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 34,
                    'name' => 'Online Admission',
                    'uri' => 'admission',
                    'type' => 1,
                    'order' => 3,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => null,
                    'name' => 'Information',
                    'uri' => '/',
                    'type' => 4,
                    'order' => 5,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 38,
                    'name' => 'Sports & Cultural Program',
                    'uri' => 'sports-n-culture-program',
                    'type' => 1,
                    'order' => 1,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 38,
                    'name' => 'Center Information',
                    'uri' => 'center-information',
                    'type' => 1,
                    'order' => 2,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 38,
                    'name' => 'Scholarship Info',
                    'uri' => 'scholarship-info',
                    'type' => 1,
                    'order' => 3,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 38,
                    'name' => 'BNCC',
                    'uri' => 'bncc',
                    'type' => 1,
                    'order' => 4,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 38,
                    'name' => 'Rover Scout',
                    'uri' => 'scout',
                    'type' => 1,
                    'order' => 5,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 38,
                    'name' => 'Tender',
                    'uri' => 'tender',
                    'type' => 1,
                    'order' => 6,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => null,
                    'name' => 'Attendance',
                    'uri' => '/',
                    'type' => 4,
                    'order' => 6,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 45,
                    'name' => 'Summery',
                    'uri' => 'attendance-summery',
                    'type' => 1,
                    'order' => 1,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 45,
                    'name' => 'Student',
                    'uri' => 'student-attendance',
                    'type' => 1,
                    'order' => 2,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 45,
                    'name' => 'Teacher & Staff',
                    'uri' => 'teacher-attendance',
                    'type' => 1,
                    'order' => 3,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => null,
                    'name' => 'News & Notice',
                    'uri' => '/',
                    'type' => 4,
                    'order' => 7,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 49,
                    'name' => 'Notice',
                    'uri' => '/notice',
                    'type' => 1,
                    'order' => 1,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 49,
                    'name' => 'News',
                    'uri' => '/news',
                    'type' => 1,
                    'order' => 2,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => null,
                    'name' => 'Gallery',
                    'uri' => '/gallery',
                    'type' => 1,
                    'order' => 8,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => null,
                    'name' => 'Download',
                    'uri' => '/download',
                    'type' => 1,
                    'order' => 9,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => null,
                    'name' => 'Contacts',
                    'uri' => '/contacts',
                    'type' => 1,
                    'order' => 10,
                    'editable' => 0,
                    'deletable' => 0,
                ],
            ];

            foreach($data as $d){
                Menu::query()->create($d);
            }
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('menus', function (Blueprint $table) {
            //
        });
    }
}
